### PR TITLE
TreeSitterClient target

### PR DESCRIPTION
**Pull request by krzyzanowskim**
A take to separate `TreeSitterClient` as a separate target and make it a dependency to Neon. Ideally, the `TreeSitterClient` could be a separate package

### CODE REVIEW

**Comment by mattmassicotte** [comment]
Thank you for putting this together!

One of the challenges with something like this is deciding which library owns which types. Do you think it makes the most sense to have both `Token` and `TextTarget` be in TreeSitterClient?

Also the platform restriction removes a lot of compatibility. I know why you did it, but I don't understand why Xcode 14 is producing a warning for this. Is it really suddenly necessary for all packages to do something like this?

**Comment by krzyzanowskim** [comment]
> Also the platform restriction removes a lot of compatibilities

right, it should list all apple platforms. also, Xcode 14 bumps the minimum target to 10.13 😭 and I've made `Package@swift-5.7.swift` to address that

**Comment by krzyzanowskim** [comment]
> Do you think it makes the most sense to have both Token and TextTarget be in TreeSitterClient?

- `Token` goes to `Neon` now
- `TextTarget` stays in TreeSitterClient. It's an `invalidationHandler` parameter and it seems to make sense there.

**Comment by krzyzanowskim** [comment]
makes sense. changed.

**Comment by mattmassicotte** [comment]
Thanks so much for doing this. Very good change!

**Pull request merged**
