### PR TITLE
Added public access to Tree in TreeSitterClient

### PR DESCRIPTION
**Pull request by kaunteya**

### CODE REVIEW

**Comment by mattmassicotte** [comment]
There are two main issues here. The first is that you must use `copy` to maintain minimal thread safety. And, this method can only be safely called on the main thread.

But, the second issue is a little higher-level. This will return the current state of the tree, which may not match the current state of the text. My guess is almost every user would want a tree that represents the text as it exists at the time the function is invoked.

It may make more sense to create a function that works more like `executeResolvingQuery(_:in:executionMode:completionHandler:)`. That way, you can guarantee that any pending edits have been processed by the time the tree is returned.

**Comment by kaunteya** [comment]
Thank you for your response, Matt.
1. I think we should return a tree when the user asks for a tree. If they want a copy they can invoke `tree?.copy()` function. Or we can convert the computed property to a function as seen below but it may not look intuitive.
```swift
func getTree(copy: Bool) {
}
````
Overall, I think copy should be more of an explicit operation so that users are aware that they will be getting a copy, even if copying is a low-cost operation in tree-sitter. Moreover, it's best to avoid side effects in computed properties. ( I believe invoking a copy() internally updates the reference count in the Nodes, instead of creating an actual copy)
Regarding thread safety, we can put a main-thread precondition.

2. Yes. I agree. Will update the PR soon for this. Also, if we have this function that guarantees integrity, then probably issues in point no.1 also will get addressed.

Let me know your thoughts.

**Comment by mattmassicotte** [comment]
The key issue is that "tree" represents internal, non-trivial state that the user cannot predict. When they ask for a "tree", what tree are they actually asking for? The state it currently happens to be in right now? TreeSitterClient might be only half-way through processing a document when you invoke it.

I see no way to guarantee predictable behavior without a little more context.

**Comment by kaunteya** [comment]
Ok. I am able to follow what you are saying.
Fetching a tree in a regular computed property is a bad idea. It is not as trivial as it looks.
I think it would be better to make an async function that will return the tree only when the pending process is complete.

On a different note, will it make any sense to expose the Tree type to the users? Could there be a more elegant way to expose all the nodes? Something like `treeSitterClient.enumerateNodes(eachNode: (Node) -> Void)`

**Comment by kaunteya** [comment]
@mattmassicotte I am trying to find a way where I should be able to determine if a tree is actively getting updated.
Should I use `hasQueuedWork` to check if there are any outstanding edits that are pending?
Can you help me with some pointers?

**Comment by mattmassicotte** [comment]
Access must follow a pattern like in `executeResolvingQuery`:

```swift
let startedVersion = version
queue.async {
    self.semaphore.wait()
    let state = self.parseState.copy()
    self.semaphore.signal()

    OperationQueue.main.addOperation {
        guard startedVersion == self.version else {
            completionHandler(.failure(.staleContent))
            return
        }

        // call a callback here
    }
}
```

**Comment by kaunteya** [comment]
I failed to understand the purpose of `version`.
As I can see, it's a private property and is initialized once to zero and never mutated again.
From what I can see `startedVersion == self.version` will always resolve to true.
Can you help me understand?

**Comment by mattmassicotte** [comment]
Gah, this is a bug! Version absolutely does need to be changed. Glad you found this!

**Comment by kaunteya** [comment]
I have added a method to fetch the tree based on your inputs.

**Comment by mattmassicotte** [comment]
Ok, I think this is really close, and a great thing to add.

I'd prefer the return type to have a non-nil tree though. In the case of nil, we can return `.failure(.stateInvalid)`.

**Comment by kaunteya** [comment]
Done

**Pull request merged**
