### PR TITLE
Fix PaintItBlack PNG reference

### LINKED ISSUE #5: Screenshot link for "painting it black" in README broken
The reference of @danielpunkass's repo and its `readme-example` folder for the "Paint it Black" screenshot is broken.

### PR DESCRIPTION
**Pull request by DivineDominion**
Closes #5 

Of course I saw the file in the root folder _after_ submitting the issue :)

### CODE REVIEW

**Comment by mattmassicotte** [comment]
Indeed there is!

`src="PaintItBlack.png?raw=true"`

**Comment by DivineDominion** [comment]
You're right -- I left the fully qualified stuff inside to make cross-fork-references possible, but didn't realize that my fork is of course based off of the current `main` where the picture exists 😅 

WDYT about the `` syntax for the image? Doesn't limit the image width, but tbh I don't know if that was intentional for a more tasteful image viewing experience, or incidental. Can revert to `` with width limit if you prefer

**Comment by mattmassicotte** [comment]
To be honest, I think this is an improvement in every way. Thanks so much for doing this!

**Comment by danielpunkass** [comment]
The explict width on the image was to achieve Retina-quality rendering of the photo. Without it, it displays at twice the size it should. At least in Safari, on my Mac.

**Pull request merged**
